name: Merge templates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Merge all template.json files to templates.json"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: templates
          path: templates

      - name: Join samples
        run: |
          jq -s '[.[]]' ./main/**/template.json > ./templates/templates.json

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./main/templates.schema.json
          INPUT_JSONS: ./templates/templates.json

      - name: Commit templates.json to templates
        uses: EndBug/add-and-commit@v9.1.3
        with:
          cwd: ./templates
          add: "templates.json --force"
          new_branch: templates
          push: true
